title: Thoughts of JHz
author: Haozhe Ji
description: Stories and thoughs to tell

highlighter: null
permalink: /:title

url: cdjhz.github.io
baseurl:

sass:
  sass_dir: public/css
  style: :compressed
