title: Thoughts of JHz
author: Haozhe Ji
description: Stories and thoughs to tell

highlighter: null
permalink: /:title

url: cdjhz.github.io
baseurl:

#define the seperator for excerpt
excerpt_separator: '<!--more-->'

#restrict posts' number per page
paginate: 10
#the style of url like "blog/page-2"
paginate_path: "blog/page-:num"
sass:
  sass_dir: public/css
  style: :compressed


markdown: kramdown
#default?
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
